name: 'supply_chain_project'
version: '1.0'
config-version: 2

profile: 'group_project'  # Matches the profile in profiles.yml

model-paths: ["models"]       # Path to the models folder
snapshot-paths: ["snapshots"]  # Path to snapshots folder
test-paths: ["tests"]         # Path to test files

models:
  supply_chain_project:
    +schema: analytics  # Use a dedicated schema for dbt models
    sales_data:
      materialized: table
    safety_stock:
      materialized: table
    monthly_sales:
      materialized: table
    inventory_efficiency:
      materialized: table
    demand_forecast:
      materialized: table
    sku_performance:
      materialized: table
