version: 2

models:
  - name: sales_data
    description: "Unified sales data combining live data and predictions"
    columns:
      - name: date_insert
        description: "Date of the sales data"
        tests:
          - not_null
      - name: sku
        description: "Stock Keeping Unit"
        tests:
          - not_null
          - unique
      - name: product_type
        description: "Type of product"
      - name: price
        description: "Price of the product"
      - name: number_of_products_sold
        description: "Number of products sold"
        tests:
          - not_null
          - accepted_range:
              min: 0
      - name: stock_levels
        description: "Stock levels"
      - name: costs
        description: "Costs associated with the product"

  - name: monthly_sales
    description: "Aggregated monthly sales data"
    columns:
      - name: sales_month
        description: "Month of the sales data"
        tests:
          - not_null
      - name: sku
        description: "Stock Keeping Unit"
        tests:
          - not_null
      - name: total_products_sold
        description: "Total number of products sold in the month"
        tests:
          - not_null
          - accepted_range:
              min: 0
      - name: average_stock_levels
        description: "Average stock levels during the month"
      - name: total_costs
        description: "Total costs incurred during the month"
      - name: average_price
        description: "Average price of the SKU during the month"
      - name: total_revenue
        description: "Total revenue generated by the SKU during the month"

semantic_models:
  - name: monthly_sales_semantic
    model: ref('monthly_sales')
    description: "Semantic model for monthly sales data"
    # primary_entity: sku  # Added primary_entity
    entities:
      - name: sku
        type: primary
    dimensions:
      - name: sales_month
        type: time
        type_params:
          time_granularity: month
      - name: product_type
        type: categorical
    measures:
      - name: total_revenue
        expr: total_revenue
        agg: sum
        agg_time_dimension: sales_month  # Set aggregation time dimension
      - name: total_products_sold
        expr: total_products_sold
        agg: sum
        agg_time_dimension: sales_month
      - name: average_stock_levels
        expr: average_stock_levels
        agg: average
        agg_time_dimension: sales_month
      - name: total_costs
        expr: total_costs
        agg: sum
        agg_time_dimension: sales_month
      - name: total_profit
        expr: total_revenue - total_costs
        agg: sum
        agg_time_dimension: sales_month
